language: php
install: true
script: true
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.webis.cool
  acl: public_read
  region: us-west-2
  on:
    repo: webiscool/home
notifications:
  email:
    on_failure: always
